---
title: "s09 Exercises: Factors"
author: "Ansley"
output: 
  html_document:
    keep_md: true
    theme: paper
---

```{r allow errors, echo = FALSE}
knitr::opts_chunk$set(error = TRUE)
```

```{r}
library(gapminder)
library(tidyverse)
```

# From Class

```{r}
#Going to look at life expectancy for the row, if it's < 23, then assign it the outcome "Very Low" for the variable we're creating. Can also add more contingencies (e.g. < 23 & "male")
gapminder %>% 
  filter(year == 1997) %>% 
  mutate(life_level = case_when(lifeExp < 23 ~ 'very low',
                                lifeExp < 48 ~ 'low',
                                lifeExp < 59 ~ 'moderate',
                                lifeExp < 70 ~ 'high',
                                # else
                                TRUE ~ 'very high')) %>% 
  ggplot() + 
  geom_boxplot(aes(x = life_level, y = gdpPercap)) +
  labs(y = "GDP per capita, $", x = "Life expectancy level, years") +
  theme_bw() 

#When R makes factors, it sorts. Here, it's sorted alphabetically, which isn't terribly useful.

```

```{r}
gapminder %>% 
  filter(year == 1997) %>% 
  mutate(life_level = factor(
                        case_when(lifeExp < 23 ~ 'very low',
                                  lifeExp < 48 ~ 'low',
                                  lifeExp < 59 ~ 'moderate',
                                  lifeExp < 70 ~ 'high',
                                  # else
                                  TRUE ~ 'very high'),
                        levels = c("very low", "low", "moderate", "high", "very high")
                        )
         ) %>%  
  ggplot() + 
  geom_boxplot(aes(x = life_level, y = gdpPercap)) +
  labs(y = "GDP per capita, $", x = "Life expectancy level, years") +
  theme_bw() +
  scale_x_discrete(drop = FALSE)
```

```{r}
class(gapminder$continent)
levels(gapminder$continent)
nlevels(gapminder$continent)
str(gapminder$continent)

#Will tell you the integer corresponding to each country:
gapminder %>% 
  pull(continent) %>% 
  as.numeric()

```


```{r}
five_country <- gapminder %>% 
  filter(country %in% c("Albania", "Argentina", "Australia", "Belgium", "Bolivia"))

nlevels(five_country$country) #Still 142- doesn't drop levels just bc no values matching. If you want to drop, use droplevels function

five_country_drop <- five_country %>% 
  droplevels()

five_country_drop$country %>%
  nlevels()
#Now just 5! 


```


```{r}
gapminder %>%
  ggplot() +
  geom_bar(aes(continent)) +
  coord_flip() +
  theme_bw() +
  ylab("Number of entries") + xlab("Continent")
```


```{r}
gapminder %>%
  ggplot() +
  geom_bar(aes(fct_infreq(continent))) + #in order of frequency 
  coord_flip() +
  theme_bw() +
  ylab("Number of entries") + xlab("Continent")


#fct_inorder() in order of appearance
#fct_inseq() in order of underlying integers
#fct_rev() in opposite order

```

```{r}
#Ordering by life expectancy

gapminder %>%
  ggplot() +
  geom_bar(aes(fct_reorder(continent, lifeExp, max))) +
  coord_flip() +
  theme_bw() +
  xlab("Continent") + ylab("Number of entries") 
```


```{r}
#Color-coding relationship between two quant variables by country

ggplot(five_country, aes(x = year, y = lifeExp,
                  color = fct_reorder2(country, year, lifeExp))) +
  geom_line() +
  labs(color = "Country")
```

```{r}
#You can rename levels specifically for your graph

gapminder %>%
  ggplot() +
  geom_bar(aes(fct_recode(continent, "OCN" = "Oceania", "AME" = "Americas"))) +
  coord_flip() +
  theme_bw()
```

```{r}
df1 <- gapminder %>%
  filter(country %in% c("United States", "Mexico"), year > 2000) %>%
  droplevels()
df2 <- gapminder %>%
  filter(country %in% c("France", "Germany"), year > 2000) %>%
  droplevels()
c(df1$country, df2$country)
fct_c(df1$country, df2$country)

```
